name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@2.31.0
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Enable Corepack
      run: corepack enable
    - name: Install NodeJS Dependencies
      run: pnpm i
    - name: Install Component Library
      run: cd storybook ; pnpm i ; cd ..
    - name: Build Component Library
      run: cd storybook ; pnpm build ; cd ..
    - name: Lint Frontend
      run: pnpm lint
    - name: Build Frontend
      run: pnpm build
    - name: Lint Frontend
      run: ./vendor/bin/pint -n --test
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
