name: Storybook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./storybook

jobs:
  storybook-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: shivammathur/setup-php@2.31.0
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Enable Corepack
      run: corepack enable
    - name: Install NodeJS Dependencies
      run: cd .. ; pnpm i ; cd storybook
    - name: Install Storybook Dependencies
      run: pnpm i
    - name: Test Component Library
      run: pnpm test -- --reporter=github-actions
    - name: Get Component Library Coverage
      run: pnpm coverage
    - name: 'Report Coverage'
      if: always()
      uses:  davelosert/vitest-coverage-report-action@v2
      with:
        name: "Storybook"
        working-directory: ./storybook
        json-summary-path: ./coverage/unit/coverage-summary.json
        json-final-path: ./coverage/unit/coverage-final.json
    - name: Build Component Library
      run: pnpm build
